List page
JulianHrt/capstone-project-Find-a-Hero pull request #9
Opened 2022-11-16 12:08 UTC by JulianHrt

Hey Guys, 
please have a look at my first PR. #1

2022-11-16 14:23 UTC, Kheirah requested changes
Very good start!

Have a look at the suggested changes and see if you can implement them.

2022-11-16 14:23 UTC, Kheirah commented on components/AdListItems/index.js
> +  });
Very good thought! If your sort function is as simple as this, you can condense everything to this:
```suggestion
  data.sort((a, b) => a .createdDate - b.createdDate);
```
This is merely a suggestion. You may leave it in its explicit form if you like.

Regardless, your code doesn't work yet because `createdDate` is of type `string`. But you need dates to do operations on. See the comment in the data.js for more info on how to do that.

2022-11-16 14:23 UTC, Kheirah commented on components/utils/data.js
> +    createdDate: "16.11.2022",
```suggestion
    createdDate: new Date(2022,10,16),
```
If you want to work with dates, you need the `date` data type.
Side note: the month starts with 0 = January which is why 10 = November.

You can apply this to every object in this array.

2022-11-17 09:53 UTC, marcbendixen approved these changes
Good job 🚀 
Made just one comment you could think about.

2022-11-17 09:53 UTC, marcbendixen commented on pages/AdListPage/index.js
> +          <AdListItems
Naming convention: Not that important but it is one item!?

`AdListItem`

2022-11-17 10:47 UTC, merged